import json

notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# Zoom Bot - Jupyter Notebook Edition\n",
                "This notebook contains the core logic for the Zoom bot, allowing you to run it directly from a Jupyter environment.\n",
                "\n",
                "**First, run the cell below to install Playwright and configure the asyncio event loop.**"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "!pip install playwright nest-asyncio faker\n",
                "!playwright install chromium\n",
                "\n",
                "import nest_asyncio\n",
                "nest_asyncio.apply()"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "**Next, define the core functions needed to join the meeting and handle the UI toggles.**"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import asyncio\n",
                "import re\n",
                "from playwright.async_api import async_playwright, TimeoutError as PlaywrightTimeoutError\n",
                "\n",
                "async def log(msg: str):\n",
                "    print(msg)\n",
                "\n",
                "async def find_first(page, selectors, timeout=8000):\n",
                "    for s in selectors:\n",
                "        try:\n",
                "            loc = page.locator(s)\n",
                "            await loc.first.wait_for(state=\"visible\", timeout=timeout)\n",
                "            return loc.first\n",
                "        except Exception:\n",
                "            continue\n",
                "    return None\n",
                "\n",
                "async def join_meeting(tag: str, page, meeting_url: str, passcode: str,\n",
                "                       name: str, wait_seconds: int,\n",
                "                       joined_event: asyncio.Event,\n",
                "                       winner_page: dict, winner_lock: asyncio.Lock,\n",
                "                       admitted_pages: list, admitted_lock: asyncio.Lock):\n",
                "    try:\n",
                "        await log(f\"{tag} 🌐 Navigating to meeting URL ...\")\n",
                "        await page.goto(meeting_url, timeout=120000, wait_until=\"domcontentloaded\")\n",
                "        await page.wait_for_timeout(3000)\n",
                "\n",
                "        # Nuke cookie banners\n",
                "        await page.evaluate(\"\"\"\n",
                "            () => document.querySelectorAll('[id*=\"onetrust\"],[class*=\"onetrust\"]')\n",
                "                          .forEach(e => e.remove())\n",
                "        \"\"\")\n",
                "\n",
                "        # Dismiss popup\n",
                "        try:\n",
                "            cancel_btn = page.locator(\"button:has-text('Cancel')\")\n",
                "            await cancel_btn.wait_for(state=\"visible\", timeout=5000)\n",
                "            await cancel_btn.click()\n",
                "            await log(f\"{tag} ✅ Dismissed popup.\")\n",
                "        except PlaywrightTimeoutError:\n",
                "            pass\n",
                "\n",
                "        await page.wait_for_timeout(1000)\n",
                "\n",
                "        # Click Join from browser\n",
                "        try:\n",
                "            join_browser_btn = page.locator(\"button:has-text('Join from browser')\")\n",
                "            await join_browser_btn.wait_for(state=\"visible\", timeout=8000)\n",
                "            await join_browser_btn.click()\n",
                "        except PlaywrightTimeoutError:\n",
                "            pass\n",
                "\n",
                "        await page.wait_for_timeout(4000)\n",
                "\n",
                "        # Passcode\n",
                "        pass_input = await find_first(page, [\n",
                "            \"#input-for-pwd\", 'input[id=\"input-for-pwd\"]', 'input[placeholder*=\"passcode\"]',\n",
                "            'input[type=\"password\"]'\n",
                "        ], timeout=5000)\n",
                "        if pass_input:\n",
                "            await pass_input.click(force=True)\n",
                "            await pass_input.fill(passcode)\n",
                "            await log(f\"{tag} 🔑 Passcode entered.\")\n",
                "\n",
                "        # Name\n",
                "        name_input = await find_first(page, [\n",
                "            \"#input-for-name\", \"#inputname\", 'input[placeholder*=\"Your Name\"]',\n",
                "        ], timeout=8000)\n",
                "        if name_input:\n",
                "            await name_input.click(force=True)\n",
                "            await name_input.fill(\"\")\n",
                "            await name_input.fill(name)\n",
                "            await log(f\"{tag} 📝 Name set to '{name}'.\")\n",
                "\n",
                "        await page.wait_for_timeout(500)\n",
                "\n",
                "        # Camera off (pre-join)\n",
                "        try:\n",
                "            cam_btn = await find_first(page, [\n",
                "                \"button#preview-video-control-button\",\n",
                "                \"button[aria-label='Stop Video']\",\n",
                "                \"button[aria-label='Turn off video']\",\n",
                "                \"button[aria-label='Start Video']\",\n",
                "                \"button:has-text('Stop Video')\",\n",
                "            ], timeout=3000)\n",
                "            if cam_btn:\n",
                "                aria_label = await cam_btn.get_attribute(\"aria-label\") or \"\"\n",
                "                btn_text   = await cam_btn.text_content() or \"\"\n",
                "                if \"Stop Video\" in aria_label or \"Turn off video\" in aria_label or \"Stop Video\" in btn_text:\n",
                "                    await cam_btn.click(force=True)\n",
                "                    await log(f\"{tag} 📷 Camera off (pre-join).\")\n",
                "                elif \"Start Video\" in aria_label or \"Start Video\" in btn_text:\n",
                "                    await log(f\"{tag} 📷 Camera already off (pre-join).\")\n",
                "        except Exception:\n",
                "            pass\n",
                "\n",
                "        # Mute mic (pre-join)\n",
                "        try:\n",
                "            mute_btn = await find_first(page, [\n",
                "                \"button#preview-audio-control-button\",\n",
                "                \"button[aria-label='Mute']\",\n",
                "                \"button[aria-label='Unmute']\",\n",
                "            ], timeout=3000)\n",
                "            if mute_btn:\n",
                "                aria_label = await mute_btn.get_attribute(\"aria-label\") or \"\"\n",
                "                if \"Mute\" in aria_label and \"Unmute\" not in aria_label:\n",
                "                    await mute_btn.click(force=True)\n",
                "                    await log(f\"{tag} 🎤 Muted (pre-join).\")\n",
                "                elif \"Unmute\" in aria_label:\n",
                "                    await log(f\"{tag} 🎤 Already muted (pre-join).\")\n",
                "        except Exception:\n",
                "            pass\n",
                "\n",
                "        await page.wait_for_timeout(300)\n",
                "\n",
                "        # Join\n",
                "        join_btn = await find_first(page, [\n",
                "            'button.preview-join-button',\n",
                "            'button[aria-label=\"Join\"]',\n",
                "            'button:has-text(\"Join\")',\n",
                "        ], timeout=6000)\n",
                "        if join_btn:\n",
                "            await join_btn.click(force=True)\n",
                "            await log(f\"{tag} ✅ Clicked Join!\")\n",
                "\n",
                "        await page.wait_for_timeout(4000)\n",
                "\n",
                "        # Post-join: camera off\n",
                "        try:\n",
                "            video_btn = await find_first(page, [\n",
                "                \"button[aria-label='Stop Video']\",\n",
                "                \"button[aria-label='Turn off video']\",\n",
                "                \"button[aria-label='Start Video']\",\n",
                "            ], timeout=5000)\n",
                "            if video_btn:\n",
                "                aria_label = await video_btn.get_attribute(\"aria-label\") or \"\"\n",
                "                if \"Stop Video\" in aria_label or \"Turn off video\" in aria_label:\n",
                "                    await video_btn.click(force=True)\n",
                "                    await log(f\"{tag} 📷 Camera turned OFF (in-meeting).\")\n",
                "        except Exception:\n",
                "            pass\n",
                "\n",
                "        # Post-join: mic off\n",
                "        try:\n",
                "            mic_btn = await find_first(page, [\n",
                "                \"button[aria-label='Mute']\",\n",
                "                \"button[aria-label='Unmute']\",\n",
                "                \"button[aria-label='Join Audio']\",\n",
                "            ], timeout=3000)\n",
                "            if mic_btn:\n",
                "                aria_label = await mic_btn.get_attribute(\"aria-label\") or \"\"\n",
                "                if \"Unmute\" in aria_label:\n",
                "                    await log(f\"{tag} 🎤 Microphone is already muted (in-meeting).\")\n",
                "                elif \"Join Audio\" in aria_label:\n",
                "                    await mic_btn.click(force=True)\n",
                "                    await log(f\"{tag} 🎤 Joined audio (in-meeting).\")\n",
                "                    await page.wait_for_timeout(2000)\n",
                "                    mute_btn = await find_first(page, [\"button[aria-label='Mute']\", \"button[aria-label='Unmute']\"], timeout=3000)\n",
                "                    if mute_btn and \"Mute\" in (await mute_btn.get_attribute(\"aria-label\") or \"\"):\n",
                "                        await mute_btn.click(force=True)\n",
                "                elif \"Mute\" in aria_label:\n",
                "                    await mic_btn.click(force=True)\n",
                "        except Exception:\n",
                "            pass\n",
                "\n",
                "        # Wait for admission\n",
                "        await log(f\"{tag} ⏳ Waiting to be admitted ...\")\n",
                "        waited = 0\n",
                "        while waited < 600:\n",
                "            if joined_event.is_set():\n",
                "                return\n",
                "            \n",
                "            in_meeting = False\n",
                "            for selector in [\".video-avatar__avatar\", \"button[aria-label='Leave']\", \"#wc-footer\"]:\n",
                "                try:\n",
                "                    if await page.locator(selector).count() > 0:\n",
                "                        in_meeting = True\n",
                "                        break\n",
                "                except Exception:\n",
                "                    pass\n",
                "            \n",
                "            if in_meeting:\n",
                "                async with admitted_lock:\n",
                "                    if page not in admitted_pages:\n",
                "                        admitted_pages.append(page)\n",
                "                async with winner_lock:\n",
                "                    if not joined_event.is_set():\n",
                "                        joined_event.set()\n",
                "                        winner_page[\"page\"] = page\n",
                "                        await log(f\"🏆 {tag} is the WINNER — '{name}'.\")\n",
                "                return\n",
                "            await page.wait_for_timeout(10000)\n",
                "            waited += 10\n",
                "    except Exception as e:\n",
                "        if not joined_event.is_set():\n",
                "            await log(f\"{tag} ❌ Error: {e}\")\n"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "**Configure inputs and run the bot coordinator!**\n",
                "\n",
                "When you run this cell, you will be prompted to enter your Meeting ID, Passcode, number of bots (10-100), and duration."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "try:\n",
                "    from faker import Faker\n",
                "except ImportError:\n",
                "    import subprocess\n",
                "    import sys\n",
                "    print(\"Installing faker...\")\n",
                "    subprocess.check_call([sys.executable, \"-m\", \"pip\", \"install\", \"faker\"])\n",
                "    from faker import Faker\n",
                "\n",
                "# Ask for meeting ID\n",
                "meeting_id = input(\"Enter Meeting ID (numbers only): \").strip()\n",
                "passcode = input(\"Enter Passcode: \").strip()\n",
                "\n",
                "# Ask for number of bots with constraints\n",
                "while True:\n",
                "    try:\n",
                "        num_tabs = int(input(\"Enter number of bots (10 to 100): \").strip())\n",
                "        if 10 <= num_tabs <= 100:\n",
                "            break\n",
                "        else:\n",
                "            print(\"Please enter a number between 10 and 100.\")\n",
                "    except ValueError:\n",
                "        print(\"Invalid input. Please enter an integer.\")\n",
                "\n",
                "# Ask for duration\n",
                "while True:\n",
                "    try:\n",
                "        stay_minutes = int(input(\"Enter duration to stay in meeting (in minutes): \").strip())\n",
                "        if stay_minutes > 0:\n",
                "            break\n",
                "        else:\n",
                "            print(\"Duration must be greater than 0.\")\n",
                "    except ValueError:\n",
                "        print(\"Invalid input. Please enter an integer.\")\n",
                "\n",
                "# Format Meeting URL properly for Web Client\n",
                "MEETING_URL = f\"https://zoom.us/wc/{meeting_id}/join?pwd={passcode}\"\n",
                "\n",
                "# Generate random Indian names\n",
                "faker_in = Faker('en_IN')\n",
                "TAB_NAMES = [faker_in.name() for _ in range(num_tabs)]\n",
                "HEADLESS = True\n",
                "\n",
                "print(f\"\\nPrepared to launch {num_tabs} bots with names like: {TAB_NAMES[:3]}...\")\n",
                "print(f\"Joining meeting {meeting_id} for {stay_minutes} minutes.\\n\")\n",
                "\n",
                "async def run_bots():\n",
                "    joined_event = asyncio.Event()\n",
                "    session_done_event = asyncio.Event()\n",
                "    winner_lock = asyncio.Lock()\n",
                "    winner_page = {\"page\": None}\n",
                "    admitted_pages = []\n",
                "    admitted_lock = asyncio.Lock()\n",
                "    \n",
                "    LAUNCH_ARGS = [\n",
                "        \"--no-sandbox\", \"--disable-setuid-sandbox\", \"--use-fake-ui-for-media-stream\",\n",
                "        \"--use-fake-device-for-media-stream\", \"--disable-gpu\", \"--window-size=1280,720\"\n",
                "    ]\n",
                "    \n",
                "    async def launch_and_join(index, name):\n",
                "        tag = f\"[Bot {index + 1}]\"\n",
                "        async with async_playwright() as p:\n",
                "            browser = await p.chromium.launch(headless=HEADLESS, args=LAUNCH_ARGS)\n",
                "            context = await browser.new_context(permissions=[\"camera\", \"microphone\"])\n",
                "            page = await context.new_page()\n",
                "            try:\n",
                "                await join_meeting(\n",
                "                    tag, page, MEETING_URL, passcode, name, stay_minutes * 60,\n",
                "                    joined_event, winner_page, winner_lock, admitted_pages, admitted_lock\n",
                "                )\n",
                "                if joined_event.is_set() and winner_page.get(\"page\") is page:\n",
                "                    await session_done_event.wait()\n",
                "            finally:\n",
                "                if not joined_event.is_set() or winner_page.get(\"page\") is not page:\n",
                "                    await browser.close()\n",
                "\n",
                "    tasks = [asyncio.create_task(launch_and_join(i, TAB_NAMES[i])) for i in range(num_tabs)]\n",
                "    \n",
                "    try:\n",
                "        await asyncio.wait_for(joined_event.wait(), timeout=660)\n",
                "    except asyncio.TimeoutError:\n",
                "        print(\"❌ No tab admitted.\")\n",
                "        for t in tasks: t.cancel()\n",
                "        return\n",
                "\n",
                "    print(f\"🟢 In meeting! Staying for {stay_minutes} minute(s).\")\n",
                "    \n",
                "    stay_seconds = stay_minutes * 60\n",
                "    for remaining in range(stay_seconds, 0, -30):\n",
                "        mins, secs = divmod(remaining, 60)\n",
                "        print(f\"⏱️  {mins:02d}:{secs:02d} remaining ...\")\n",
                "        await asyncio.sleep(min(30, remaining))\n",
                "        \n",
                "    print(\"👋 Time is up! Leaving the meeting ...\")\n",
                "    try:\n",
                "        wp = winner_page[\"page\"]\n",
                "        leave = wp.locator(\"button[aria-label='Leave'], button[aria-label='End'], button:has-text('Leave')\")\n",
                "        await leave.first.wait_for(state=\"visible\", timeout=5000)\n",
                "        await leave.first.click()\n",
                "        await wp.wait_for_timeout(1500)\n",
                "        confirm = wp.locator(\"button:has-text('Leave Meeting'), button:has-text('Leave for Everyone')\")\n",
                "        await confirm.first.click()\n",
                "        print(\"✅ Left the meeting.\")\n",
                "    except Exception as e:\n",
                "        print(f\"⚠️ Leave error: {e}\")\n",
                "        \n",
                "    session_done_event.set()\n",
                "    await asyncio.sleep(2)\n",
                "    for t in tasks: t.cancel()\n",
                "\n",
                "# Run the bots\n",
                "await run_bots()"
            ]
        }
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "name": "python",
            "version": "3.10"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 4
}

with open("zoom_bot.ipynb", "w") as f:
    json.dump(notebook, f, indent=2)
